In [566]:
# Cel zadania

In [567]:
#### Celem zadania było zrozumienie, oczyszczenie i przeanalizowanie dostarczonego zbioru danych.
#### Zbiorem roboczym jest "TitanicMess.tsv".

In [568]:
# 1) Import bibliotek

In [569]:
import pandas as pd
import statistics

In [570]:
#### Wczytanie roboczego zbioru danych.

In [571]:
tit = pd.read_csv('E:\SIWB\TitanicMess.tsv', sep = '\t')

In [572]:
#### Wyświetlenie zbioru za pomocą display'a w celu zapoznania się z zawartością pliku.

In [573]:
display(tit)

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   
891         1000         1       1   

                                                  Name     Sex  Age  SibSp  \
0                              Braund, Mr. Owen Harris    male   22      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38      1   
2                               Heikkinen, Miss. Laina  female   26      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35      1   
4                             Allen, Mr. William Henry    male   35      0   
..                                                 ...     ...  ...    ...   
887                       Graham, Miss. Margaret Edith  female   19      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female  NaN      1   
889                              Behr, Mr. Karl Howell    male   26      0   
890                                Dooley, Mr. Patrick    male   32      0   
891                        Mr. Frederick Maxfield Hoyt    male   38      1   

     Parch            Ticket     Fare Cabin Embarked     ship  
0        0         A/5 21171     7,25   NaN        S  Titanic  
1        0          PC 17599  71,2833   C85        C  Titanic  
2        0  STON/O2. 3101282    7,925   NaN        S  Titanic  
3        0            113803     53,1  C123        S  Titanic  
4        0            373450     8,05   NaN        S  Titanic  
..     ...               ...      ...   ...      ...      ...  
887      0            112053       30   B42        S  Titanic  
888      2        W./C. 6607    23,45   NaN        S  Titanic  
889      0            111369       30  C148        C  Titanic  
890      0            370376     7,75   NaN        Q  Titanic  
891      0             19943       90   C93        S  Titanic  

[892 rows x 13 columns]

In [574]:
#### Wykorzystanie funkcji "head" oraz "tail" dla lepszej czytelności.


In [575]:
display(tit.head(5))

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38      1   
2                             Heikkinen, Miss. Laina  female  26      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35      1   
4                           Allen, Mr. William Henry    male  35      0   

   Parch            Ticket     Fare Cabin Embarked     ship  
0      0         A/5 21171     7,25   NaN        S  Titanic  
1      0          PC 17599  71,2833   C85        C  Titanic  
2      0  STON/O2. 3101282    7,925   NaN        S  Titanic  
3      0            113803     53,1  C123        S  Titanic  
4      0            373450     8,05   NaN        S  Titanic

In [576]:
display(tit.tail(5))

PassengerId  Survived  Pclass                                      Name  \
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   
891         1000         1       1               Mr. Frederick Maxfield Hoyt   

        Sex  Age  SibSp  Parch      Ticket   Fare Cabin Embarked     ship  
887  female   19      0      0      112053     30   B42        S  Titanic  
888  female  NaN      1      2  W./C. 6607  23,45   NaN        S  Titanic  
889    male   26      0      0      111369     30  C148        C  Titanic  
890    male   32      0      0      370376   7,75   NaN        Q  Titanic  
891    male   38      1      0       19943     90   C93        S  Titanic

In [577]:
#### Na pierwszy rzut oka widać, że w kolumnach "Age", "Cabin" występuje brak danych, a także jedna zmienna w kolumnie "ship".

In [578]:
#### Potwierdzamy, że w kolumnie "ship" jest wyłącznie jedna zmienna, która nie jest ważna w analizie zbioru.  

In [579]:
print(tit['ship'].unique())

['Titanic']


In [580]:
#### Dla analizy zbioru nie są konieczne również kolumny "Name" oraz "Ticket".

In [581]:
#### Tworzymy zatem tabele pozbawioną powyższych kolumn.

In [582]:
tit = tit[['PassengerId', 'Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']]

In [583]:
# Czyszczenie danych

In [584]:
#### Wyrzucamy wszystkie 'NA' w tabeli.

In [585]:
def drop_na(tita):

    tit = len(tita)
    tita = tita.dropna()
    print("NA dropped: {}".format(tit - len(tita)))
      
tita = drop_na(tit)

NA dropped: 175


In [586]:
#### Wyrzucamy wszystkie duplikaty w tabeli.

In [587]:
def drop_dupl(tita):
    
    duplicate = len(tita[tita['PassengerId'].duplicated()])
    if duplicate > 0:
        tita = tita.drop_duplicates(subset = 'PassengerId', keep="last")
        print ("Duplicates dropped: {}".format(duplicate))
        return tita
    else:
        return tita
    
tita = drop_dupl(tit)

Duplicates dropped: 4


In [588]:
#### Sprawdzamy czy zabieg się udał.

In [589]:
tita[tita.duplicated()]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Sex, Age, SibSp, Parch, Fare, Embarked]
Index: []

In [590]:
#### Patrzymy jak aktualnie prezentuje się nasz zbiór danych.

In [591]:
tita.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 888 entries, 0 to 891
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   PassengerId  888 non-null    int64 
 1   Survived     888 non-null    int64 
 2   Pclass       888 non-null    int64 
 3   Sex          888 non-null    object
 4   Age          715 non-null    object
 5   SibSp        888 non-null    int64 
 6   Parch        888 non-null    int64 
 7   Fare         888 non-null    object
 8   Embarked     886 non-null    object
dtypes: int64(5), object(4)
memory usage: 69.4+ KB


In [592]:
#Widać niespójności w typach danych w kilku kolumnach. Sprawdzamy wartości unikalne dla każej z kolumn. 

In [593]:
tita.PassengerId.unique()

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   12,
         13,   15,   16,   17,   18,   19,   20,   21,   22,   23,   11,
         25,   26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
         36,   37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
         47,   48,   49,   50,   51,   52,   53,   54,   55,   56,   57,
         58,   59,   60,   61,   62,   63,   64,   65,   66,   67,   68,
         69,   70,   71,   72,   73,   74,   75,   76,   77,   78,   79,
         80,   81,   82,   83,   84,   85,   86,   87,   88,   89,   90,
         91,   92,   93,   94,   95,   96,   97,   98,   99,  100,  101,
        102,  103,  104,  105,  106,  107,  108,  109,  110,  111,  112,
        113,  114,  115,  116,  117,  118,  119,  120,  121,  122,  123,
        124,  125,  126,  127,  128,  129,  130,  131,  132,  133,  134,
        135,  136,  137,  138,  139,  140,  141,  142,  143,  144,  145,
        146,  147,  148,  149,  150,  151,  152,  1

In [594]:
tita.Survived.unique()

array([0, 1], dtype=int64)

In [595]:
tita.Pclass.unique()

array([3, 1, 2], dtype=int64)

In [596]:
tita.Sex.unique()

array(['male', 'female', 'malef', 'mal', 'fem', 'femmale'], dtype=object)

In [597]:
##### Kolumna "Sex" wymaga manualnej korekcji, ponieważ występują w niej literówki.

In [598]:
tita = tita.copy()
tita['Sex'] = tita['Sex'].replace({'malef': 'male', 'mal': 'male', 'femmale': 'female','fem' : 'female'})

In [599]:
print(tita['Sex'].unique())

['male' 'female']


In [600]:
#### Udało się naprawić kolumne "Sex".

In [601]:
tita.SibSp.unique()

array([1, 0, 3, 4, 2, 5, 8], dtype=int64)

In [602]:
tita.Parch.unique()

array([0, 1, 2, 5, 3, 4], dtype=int64)

In [603]:
tita.Fare.unique()

array(['7,25', '71,2833', '7,925', '53,1', '8,05', '8,4583', '51,8625',
       '21,075', '11,1333', '30,0708', '26,55', '7,8542', '16', '29,125',
       '13', '18', '7,225', '26', '8,0292', '16,7', '31,3875', '263',
       '7,8792', '7,8958', '27,7208', '146,5208', '7,75', '10,5',
       '82,1708', '52', '7,2292', '11,2417', '9,475', '21', '41,5792',
       '15,5', '21,6792', '17,8', '39,6875', '7,8', '76,7292', '61,9792',
       '35,5', '27,75', '46,9', '80', '83,475', '27,9', '15,2458',
       '8,1583', '8,6625', '73,5', '14,4542', '56,4958', '7,65', '29',
       '12,475', '9', '9,5', '7,7875', '47,1', '15,85', '34,375',
       '61,175', '20,575', '34,6542', '63,3583', '23', '77,2875',
       '8,6542', '7,775', '24,15', '9,825', '14,4583', '247,5208',
       '31,275', '7,1417', '22,3583', '6,975', '7,05', '14,5', '15,0458',
       '26,2833', '9,2167', '79,2', '6,75', '11,5', '36,75', '7,7958',
       '12,525', '66,6', '7,3125', '61,3792', '7,7333', '69,55', '16,1',
       '15,75', '2

In [604]:
#### Podobny problem jak w kolumnie "Sex" w kolumnie "Embarked". Wymaga manualnej korekcji.

In [605]:
tita.Embarked.unique()

array(['S', 'C', 'Q', 'So', nan, 'Co', 'Qe'], dtype=object)

In [606]:
tita = tita.copy()
tita['Embarked'] = tita['Embarked'].replace({'So':'S', 'Qe':'Q', 'Co':'C', 'nan':'NaN'})


In [607]:
tita.Embarked.unique()


array(['S', 'C', 'Q', nan], dtype=object)

In [608]:
#### Udało się częściowo poprawić kolumne, pozostał jeszcze 'nan', który można usunąć za pomocą "pandas dropna by inplace"

In [609]:
tita.dropna(inplace=True)


In [610]:
tita.Embarked.unique()


array(['S', 'C', 'Q'], dtype=object)

In [611]:
#### Udało się, mamy właściwie poprawioną kolumnę. 

In [612]:
tita.Survived.unique()

array([0, 1], dtype=int64)

In [613]:
tita.Age.unique()

array(['22', '38', '26', '35', '54', '2', '27', '14', '58', '20', '55',
       '31', '34', '15', '4', '8', '19', '40', '.9', '66', '28', '42',
       '21', '18', '3', '7', '49', '29', '65', '28,5', '5', '11', '45',
       '17', '32', '16', '25', '0,83', '30', '33', '23', '24', '46', '59',
       '71', '37', '47', '14,5', '70,5', '32,5', '12', '9', '36,5', '51',
       '55,5', '40,5', '44', '1', '61', '56', '50', '36', '45,5', '4435',
       '20,5', '62', '41', '52', '63', '23,5', '0,92', '43', '60', '39',
       '10', '64', '13', '48', '0,75', '-3', '-12', '53', '57', '80',
       '250', '70', '24,5', '6', '0,67', '30,5', '0,42', '34,5', '74'],
      dtype=object)

In [614]:
#### Podczas monitorowania kolumny "Age" widać niespójności w danych: 
#### 1) Występują wartości nieralne (4435, 250)
#### 2) Oraz wiek jest podany w wartościach dziesiętnych i ujemnych

In [615]:
tAge = tita['Age'].value_counts().to_dict()

In [616]:
display(tAge)

{'24': 30,
 '22': 27,
 '18': 26,
 '19': 25,
 '28': 24,
 '30': 24,
 '21': 24,
 '25': 22,
 '36': 22,
 '29': 20,
 '27': 18,
 '26': 18,
 '32': 18,
 '35': 18,
 '16': 17,
 '31': 17,
 '34': 15,
 '23': 15,
 '20': 15,
 '33': 15,
 '39': 13,
 '42': 13,
 '40': 13,
 '17': 13,
 '45': 12,
 '38': 11,
 '2': 10,
 '4': 10,
 '50': 10,
 '44': 9,
 '48': 9,
 '47': 9,
 '54': 8,
 '9': 8,
 '1': 7,
 '51': 7,
 '41': 6,
 '52': 6,
 '37': 6,
 '49': 6,
 '3': 6,
 '14': 6,
 '15': 5,
 '58': 5,
 '43': 4,
 '60': 4,
 '8': 4,
 '56': 4,
 '5': 4,
 '11': 4,
 '6': 3,
 '46': 3,
 '65': 3,
 '7': 3,
 '62': 3,
 '61': 3,
 '70': 2,
 '64': 2,
 '0,83': 2,
 '55': 2,
 '59': 2,
 '0,75': 2,
 '28,5': 2,
 '57': 2,
 '63': 2,
 '40,5': 2,
 '10': 2,
 '32,5': 2,
 '13': 2,
 '45,5': 2,
 '71': 2,
 '30,5': 2,
 '0,92': 1,
 '250': 1,
 '0,42': 1,
 '53': 1,
 '0,67': 1,
 '.9': 1,
 '66': 1,
 '4435': 1,
 '23,5': 1,
 '20,5': 1,
 '70,5': 1,
 '24,5': 1,
 '14,5': 1,
 '-3': 1,
 '80': 1,
 '74': 1,
 '12': 1,
 '34,5': 1,
 '55,5': 1,
 '36,5': 1,
 '-12': 1}

In [617]:
tita = tita[tita.Age.apply(lambda x: x.isnumeric())]

In [618]:
tita = tita.astype({'Age': int, 'Survived': bool})

In [619]:
print(tita[tita['Age'] > 100])
tita = tita[tita['Age'] < 100]

     PassengerId  Survived  Pclass   Sex   Age  SibSp  Parch    Fare Embarked
223          224     False       3  male  4435      0      0  7,8958        S
666          667     False       2  male   250      0      0      13        S


In [620]:
print('min_age :', tita['Age'].min(),' <<--->> ',tita['Age'].max(),": max_age")

min_age : 1  <<--->>  80 : max_age


In [621]:
#### Sprawdzamy poraz kolejny jak wyglada kolumna.


In [622]:
tita

PassengerId  Survived  Pclass     Sex  Age  SibSp  Parch     Fare  \
0              1     False       3    male   22      1      0     7,25   
1              2      True       1  female   38      1      0  71,2833   
2              3      True       3  female   26      0      0    7,925   
3              4      True       1  female   35      1      0     53,1   
4              5     False       3    male   35      0      0     8,05   
..           ...       ...     ...     ...  ...    ...    ...      ...   
886          887     False       2    male   27      0      0       13   
887          888      True       1  female   19      0      0       30   
889          890      True       1    male   26      0      0       30   
890          891     False       3    male   32      0      0     7,75   
891         1000      True       1    male   38      1      0       90   

    Embarked  
0          S  
1          C  
2          S  
3          S  
4          S  
..       ...  
886        S  
887        S  
889        C  
890        Q  
891        S  

[683 rows x 9 columns]

In [623]:
#### Sprawdzamy ponownie wartości unikalne zbioru.

In [624]:
def finalTest(test):
    
    try:
        print(10*">" + ' ' + test + ' ' +10*"<")
        print(45*'-')
        print('')
    except:
        print('Error')
        
def valueCounts(tita):
    
    num_of_cols = len(tita.columns)
    
    for i, j in enumerate(tita.columns):
        print('')
        print('')
        print(10*'*',j,10*'*')
        finalTest("Test --> {}".format(j))
        print(tita[j].value_counts())

In [625]:
valueCounts(tita)



********** PassengerId **********
>>>>>>>>>> Test --> PassengerId <<<<<<<<<<
---------------------------------------------

1000    1
295     1
312     1
311     1
310     1
       ..
600     1
598     1
596     1
595     1
1       1
Name: PassengerId, Length: 683, dtype: int64


********** Survived **********
>>>>>>>>>> Test --> Survived <<<<<<<<<<
---------------------------------------------

False    404
True     279
Name: Survived, dtype: int64


********** Pclass **********
>>>>>>>>>> Test --> Pclass <<<<<<<<<<
---------------------------------------------

3    336
1    181
2    166
Name: Pclass, dtype: int64


********** Sex **********
>>>>>>>>>> Test --> Sex <<<<<<<<<<
---------------------------------------------

male      431
female    252
Name: Sex, dtype: int64


********** Age **********
>>>>>>>>>> Test --> Age <<<<<<<<<<
---------------------------------------------

24    30
22    27
18    26
19    25
30    24
      ..
74     1
66     1
12     1
53     1
80     1
Nam

In [626]:
#### Wydaje się, że plik został oczyszczony właściwie.

In [627]:
#### Na koniec zapisujemy finalny plik do "TitanicCleaned.tsv"

In [628]:
tita.to_csv('TitanicCleaned.tsv', index = False)

In [629]:
# Wnioski

In [630]:
#### Roboczy zestaw danych wymagał kilku istotnych zabiegów by doprowadzić go do właściwej formy. Należało usunąć wiersze z brakującymi danycmi, usunąć duplikaty, zmienić typy danych w konkretnych kolumnach a także usunięcia kolumn nieistotnych w analizie. 